services:
  - name: db
    image: postgres:15-alpine
    envVars:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    restartPolicy:
      type: unless-stopped
    volumes:
      - name: db-data
        path: /var/lib/postgresql/data

  - name: wiki
    image: ghcr.io/requarks/wiki:2
    envVars:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    dependencies:
      - name: db
    restartPolicy:
      type: unless-stopped
    ports:
      - 80:3000

volumes:
  - name: db-data
